### ISSUE TITLE
2.14 보고올 것

### ISSUE THREAD

**Issue by bestowing** [Suin-Bundang/wwdc-study#1]
링크
- https://developer.apple.com/videos/play/wwdc2017/715/
- https://developer.apple.com/videos/play/wwdc2021/10180/

**Comment by mandeuk26** [comment]
Commits
- 04c7783ba39117d9bf98e55c9cbdb5cf7f1d7cd5
- e5ae47be48fadf54007f05a87d6603a6b09b9137
